### ISSUE TITLE
Security Review Doc

### ISSUE THREAD

**Issue by jillian-k** [SFDO-Community-Sprints/sticky-selectron-documentation#11]
[Security Review Doc](https://docs.google.com/document/d/1IfXF0fAh0Z_pSnn3e6OTqMhFdDEqvfJflo0M353aB38/edit?usp=sharing)

Create a doc to answer Security Review questions.

[Quip: Sticky Selectron OSC Security Review Checklist](https://terranox.quip.com/yprMA4E5uoFb/Sticky-Selectron-OSC-Security-Review-Checklist)

**Comment by pickettd** [comment]
The first stab at answers for this doc are now completed in the Google doc

**Comment by pickettd** [comment]
Sounds like Cori expressed that our doc provided is good enough for now
